package web

type ServiceGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.

	NotesInfoService
	UserLevelPriceService
	MemberInterestsService
	ContactUsService
	PlatformRegisterService
	UserInfoService
	OrderService
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
