package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.

	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
