package common

type RouterGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.
	CommonRouter
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
