package common

type ApiGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.
	CommonApi
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
