package web

type RouterGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.

	NotesInfoRouter
	UserLevelPriceRouter
	MemberInterestsRouter
	ContactUsRouter
	PlatformRegisterRouter
	UserInfoRouter
	OrderRouter
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
