package web

type ApiGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.

	NotesInfoApi
	UserLevelPriceApi
	MemberInterestsApi
	ContactUsApi
	PlatformRegisterApi
	UserInfoApi
	OrderApi
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
