package course

type ServiceGroup struct {
	// Code generated by github.com/opisnoeasy/course-service Begin; DO NOT EDIT.

	CourseInfoService
	CourseSectionService
	// Code generated by github.com/opisnoeasy/course-service End; DO NOT EDIT.
}
